# Generated by Django 3.2.9 on 2021-11-24 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('borrow_status', models.IntegerField(default=1)),
                ('return_status', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('endtime', models.DateTimeField(default=datetime.datetime.now)),
                ('starttime', models.DateTimeField(default=datetime.datetime.now)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
